name: minimal

on:
    push
jobs:
    idle:
        name: log idle name of the setup
        runs-on: ubuntu-latest
        steps:
            -
                name: prereq
                run: |
                    echo Idle step
                    apt update
                    apt install sowsay
            -
                name: usage
                run: |
                    echo Finishig Step
